apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  namespace: healthcheck
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: user03acr.azurecr.io/reservation:latest
          ports:
            - containerPort: 8080
          env:
            - name: configurl
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: url
          resources:
            limits:
              cpu : 500m
            requests: 
              cpu : 200m